// 系统常量
// author xiaoRui

package constant

const (
	ContextKeyUserObj      = "authedUserObj"
	LOGIN_CODE             = "login_code:"
	INVALID_PARAMS         = 400
	GROUP_EXIST            = 415
	ECS_AUTH_CREATE_FAILED = 416
	ECS_AUTH_UPDATE_FAILED = 417
	ECS_AUTH_DELETE_FAILED = 418
	ECS_AUTH_NAME_EXISTS   = 419
	ECS_AUTH_NOT_FOUND     = 420

	// CMDB主机相关错误码
	CMDB_HOST_CREATE_FAILED = 421
	CMDB_HOST_UPDATE_FAILED = 422
	CMDB_HOST_DELETE_FAILED = 423
	CMDB_HOST_NAME_EXISTS   = 424
	CMDB_HOST_NOT_FOUND     = 425
	CMDB_HOST_AUTH_NOT_FOUND = 426
	CMDB_HOST_AUTH_FAILED   = 427
	CMDB_HOST_SYNC_FAILED   = 428
	CMDB_IMPORT_TASK_CREATE_FAILED = 429
	FILE_OPERATION_ERROR    = 430 // 文件操作失败

	// CI 动态模型相关错误码
	CI_TYPE_CREATE_FAILED    = 440
	CI_TYPE_UPDATE_FAILED    = 441
	CI_TYPE_DELETE_FAILED    = 442
	CI_TYPE_NOT_FOUND        = 443
	CI_TYPE_CODE_EXISTS      = 444
	CI_ATTR_CREATE_FAILED    = 445
	CI_ATTR_UPDATE_FAILED    = 446
	CI_ATTR_DELETE_FAILED    = 447
	CI_INSTANCE_CREATE_FAILED = 450
	CI_INSTANCE_UPDATE_FAILED = 451
	CI_INSTANCE_DELETE_FAILED = 452
	CI_INSTANCE_NOT_FOUND    = 453
	CI_RELATION_CREATE_FAILED = 455
	CI_RELATION_DELETE_FAILED = 456

	// Project 项目管理相关错误码
	PROJECT_CREATE_FAILED = 460
	PROJECT_UPDATE_FAILED = 461
	PROJECT_DELETE_FAILED = 462
	PROJECT_NOT_FOUND     = 463
	PROJECT_CODE_EXISTS   = 464
	PROJECT_HAS_RESOURCES = 465 // 项目下存在关联资源，无法删除

	// Kubernetes集群相关常量
	KUBE_CLUSTER_CODE         = "kube_cluster:"
	KUBE_CLUSTER_CACHE_CODE   = "kube_cluster_cache:"
)
